'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';
const ideas=[
{topic:'猛暑でも枯れにくい庭',trend:94,aio:91,fit:96,reason:'酷暑・節水・ドライガーデンの検索意図が一致'},
{topic:'食料価格高騰と家庭菜園',trend:90,aio:95,fit:92,reason:'ニュース性とVictory Garden文脈を接続できる'},
{topic:'ロストラータの育て方',trend:76,aio:93,fit:100,reason:'指名検索と実体験コンテンツに強い'},
{topic:'庭で始める食育',trend:82,aio:89,fit:95,reason:'親子・教育・家庭菜園の複合需要'},
{topic:'夜の庭をワインバーにする',trend:71,aio:74,fit:98,reason:'保存されやすいライフスタイル企画'}];
export default function Page(){const [query,setQuery]=useState('庭・食・風・岡沢町');const ranked=useMemo(()=>ideas.map(x=>({...x,total:Math.round(x.trend*.35+x.aio*.35+x.fit*.3)})).sort((a,b)=>b.total-a.total),[]);return <main style={{minHeight:'100vh',background:'#080a0d',color:'#f4f4ef',padding:28}}><div style={{maxWidth:1180,margin:'auto'}}><Link href="/sunset-deck" style={{color:'#aebba5'}}>← STUDIO OS</Link><p style={{marginTop:32,letterSpacing:'.18em',fontSize:11,color:'#9fab95'}}>TREND + AIO OPPORTUNITY ENGINE</p><h1 style={{fontSize:'clamp(36px,7vw,72px)',margin:'8px 0'}}>What should we make now?</h1><p style={{color:'#9aa1a8'}}>公開データ接続前の初版スコアリング画面。Google Trends、Yahoo!リアルタイム、YouTube、SNS入力を同じ形式へ正規化する設計です。</p><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:10,padding:18,border:'1px solid #29312d',borderRadius:16,background:'#101411'}}><input value={query} onChange={e=>setQuery(e.target.value)} style={{background:'#080a0d',border:'1px solid #343b37',borderRadius:10,padding:14,color:'#fff'}}/><button style={{border:0,borderRadius:10,padding:'0 20px',background:'#d6c39a',fontWeight:800}}>SCAN</button></div><div style={{display:'grid',gap:12,marginTop:22}}>{ranked.map((x,i)=><article key={x.topic} style={{display:'grid',gridTemplateColumns:'64px 1fr auto',gap:18,alignItems:'center',padding:18,border:'1px solid #252c29',borderRadius:15,background:'#0d1012'}}><strong style={{fontSize:30}}>0{i+1}</strong><div><h2 style={{margin:'0 0 4px'}}>{x.topic}</h2><p style={{margin:0,color:'#9aa1a8'}}>{x.reason}</p><small style={{color:'#cdbb91'}}>Trend {x.trend} / AIO {x.aio} / Brand Fit {x.fit}</small></div><div style={{fontSize:28,fontWeight:900,color:'#d6c39a'}}>{x.total}</div></article>)}</div><section style={{marginTop:22,padding:20,border:'1px solid #3a3323',borderRadius:15,background:'#15130e'}}><h2 style={{marginTop:0}}>今日の推奨</h2><p>第1話は「食料価格高騰 × Victory Garden × 岡沢町の風」を軸に公開し、ショートでは「もし明日スーパーから食べ物が消えたら」を冒頭フックとして展開します。</p></section></div></main>}
