export type ProductionScene = {
  id: number;
  time: string;
  duration: number;
  chapter: string;
  visual: string;
  narration: string;
  imagePrompt: string;
  videoPrompt: string;
  sound: string;
  caption?: string;
};

const STYLE = '16:9 cinematic American pop editorial illustration, realistic architectural textures, bold graphic shadows, restrained stencil accents, warm amber and deep navy palette, calm lo-fi atmosphere, premium dark wooden architecture, California dry garden, hand-drawn cream wind lines moving left to right, no logos, no text, no signage';
const MOTION = 'slow cinematic camera movement, subtle parallax, wind moving left to right, hand-drawn wind lines drifting naturally, plants gently swaying, smoke and dust moving softly, no rapid motion, seamless documentary shot';

export const ep01Scenes: ProductionScene[] = [
  {id:1,time:'00:00–00:12',duration:12,chapter:'HOOK',visual:'停電した都市。閉じたスーパーの前を風だけが通り抜ける。',narration:'もし明日、スーパーから食べ物が消えたら。私たちは、どこへ向かうのでしょう。',imagePrompt:`${STYLE}. Empty Japanese supermarket at night after a blackout, shutters closed, scattered paper moving in the wind, wide negative space, dramatic shadows.`,videoPrompt:`${MOTION}. Push slowly toward the closed entrance; loose receipt paper crosses frame.`,sound:'低い風音、遠い電気ノイズ、単音ピアノ',caption:'もし明日、食べ物が消えたら。'},
  {id:2,time:'00:12–00:25',duration:13,chapter:'HOOK',visual:'岡沢町の夜。黒い家とロストラータ。線で描かれた風が庭を横切る。',narration:'ここ、横浜・岡沢町では、今夜も風が庭を渡っています。',imagePrompt:`${STYLE}. Night view of a modern black wooden house in Okazawa, Yokohama, illuminated Yucca rostrata and agave garden, broad dark sky, elegant hand-drawn wind lines.`,videoPrompt:`${MOTION}. Slow lateral move across the garden; warm lights flicker slightly.`,sound:'岡沢町の風、ローファイの柔らかなキック'},
  {id:3,time:'00:25–00:40',duration:15,chapter:'HOOK',visual:'土に触れる手。乾いた土が風にほどける。',narration:'土は、古い答えを知っています。人が何度も忘れ、そのたびに思い出してきた答えを。',imagePrompt:`${STYLE}. Close-up of adult hands touching dry garden soil, tiny dust particles and drawn wind lines, warm side light, contemplative mood.`,videoPrompt:`${MOTION}. Macro push-in; soil grains lift lightly in the breeze.`,sound:'土の擦れる音、呼吸、薄いレコードノイズ'},
  {id:4,time:'00:40–00:55',duration:15,chapter:'ACT 1',visual:'現代の物流網。高速道路、港、倉庫が一本の線でつながる。',narration:'私たちの食卓は、遠くの畑、港、道路、倉庫によって支えられています。',imagePrompt:`${STYLE}. Stylized aerial collage of farms, port, highways and warehouse connected by stencil-like lines, American editorial poster composition.`,videoPrompt:`${MOTION}. Camera glides over the connected supply chain; lines pulse subtly.`,sound:'遠いトラック音、控えめなベース'},
  {id:5,time:'00:55–01:10',duration:15,chapter:'ACT 1',visual:'空になった棚の影。缶詰が一つだけ残っている。',narration:'便利さは強さに見えます。しかし、ひとつの線が止まれば、棚は驚くほど早く空になります。',imagePrompt:`${STYLE}. Nearly empty grocery shelves, one can remaining, graphic long shadows, muted cream and amber highlights.`,videoPrompt:`${MOTION}. Slow dolly past empty shelves; overhead light hums.`,sound:'蛍光灯のハム音、遠いカート音'},
  {id:6,time:'01:10–01:27',duration:17,chapter:'ACT 1',visual:'ニュース断片、嵐、道路封鎖、停電。',narration:'戦争だけではありません。災害、異常気象、燃料不足。食料の流れは、いつでも揺らぐ可能性があります。',imagePrompt:`${STYLE}. Editorial montage of storm clouds, blocked road, dark city blocks and disrupted transport, tasteful stencil overlays.`,videoPrompt:`${MOTION}. Slow layered parallax across the montage; smoke drifts gently.`,sound:'風が強まる、低いドローン'},
  {id:7,time:'01:27–01:42',duration:15,chapter:'ACT 1',visual:'1940年代へ切り替わる古いラジオ。',narration:'約80年前、人々は同じ不安の中で、ラジオから流れる呼びかけを聞いていました。',imagePrompt:`${STYLE}. 1940s tabletop radio in a dim American kitchen, warm lamp, smoke curling upward, vintage poster shading.`,videoPrompt:`${MOTION}. Slow push toward the radio dial; smoke and curtain move in the breeze.`,sound:'AMラジオのノイズ、時代感のある弦'},
  {id:8,time:'01:42–01:58',duration:16,chapter:'ACT 2',visual:'芝生を掘り返す家族。',narration:'庭を耕してください。野菜を育ててください。それは、家庭のためであり、国のためでもある。',imagePrompt:`${STYLE}. 1940s family transforming a front lawn into a vegetable garden, optimistic American poster energy, bold shadows, no propaganda text.`,videoPrompt:`${MOTION}. Gentle pan as family members dig and plant; wind lifts clothing edges.`,sound:'シャベル、鳥、ブラシドラム'},
  {id:9,time:'01:58–02:13',duration:15,chapter:'ACT 2',visual:'Victory Gardenの種袋、シャベル、手袋。',narration:'こうして生まれたのが、ビクトリー・ガーデン。勝利の庭です。',imagePrompt:`${STYLE}. Seed packets, worn gloves and shovel arranged on a wooden table, 1940s American pop poster composition, no readable text.`,videoPrompt:`${MOTION}. Top-down slow orbit; paper corners flutter.`,sound:'紙の音、軽いスネアブラシ',caption:'VICTORY GARDEN'},
  {id:10,time:'02:13–02:29',duration:16,chapter:'ACT 2',visual:'学校、工場、住宅地の空き地が畑に変わる。',narration:'家庭の裏庭だけではありません。学校の校庭も、工場の空き地も、公園の一角も畑になりました。',imagePrompt:`${STYLE}. Triptych showing schoolyard, factory lot and public park converted into vegetable plots, unified vintage editorial style.`,videoPrompt:`${MOTION}. Slow move across three connected panels; wind lines link them.`,sound:'子どもの声、遠い工場音、アコースティックギター'},
  {id:11,time:'02:29–02:45',duration:16,chapter:'ACT 2',visual:'芽が土を押し上げる。',narration:'小さな種は、食料だけではなく、安心を育てました。',imagePrompt:`${STYLE}. Macro seedling breaking through dark soil, warm dawn light, graphic shadow, delicate wind lines.`,videoPrompt:`${MOTION}. Timelapse-like but slow sprout movement; dust drifts.`,sound:'土の微細音、明るいピアノ和音'},
  {id:12,time:'02:45–03:02',duration:17,chapter:'ACT 2',visual:'収穫した野菜を近所で分け合う。',narration:'育て方を教え、種を分け、余った収穫を隣人へ渡す。庭は、人と人をつなぐ場所になりました。',imagePrompt:`${STYLE}. Neighbors sharing baskets of vegetables over a low fence, warm human expressions, American pop illustration with realistic texture.`,videoPrompt:`${MOTION}. Slow handheld-style drift; leaves and apron move in wind.`,sound:'穏やかな会話、籠の音、ジャズコード'},
  {id:13,time:'03:02–03:18',duration:16,chapter:'ACT 2',visual:'子どもが土からニンジンを抜く。',narration:'子どもたちは、食べ物が棚から生まれるのではないことを、手の感触で覚えました。',imagePrompt:`${STYLE}. Child pulling a carrot from soil, delighted but natural expression, warm vintage editorial scene, bold shadow.`,videoPrompt:`${MOTION}. Slow close-up; carrot lifts, soil falls, wind moves hair.`,sound:'土、子どもの小さな笑い声'},
  {id:14,time:'03:18–03:35',duration:17,chapter:'ACT 2',visual:'夕暮れの共同菜園。遠くに街の灯り。',narration:'それは食育という言葉より前から存在した、生活そのものの学びでした。',imagePrompt:`${STYLE}. Community garden at dusk, distant city lights, people tending plots, calm wine-bar-like amber atmosphere.`,videoPrompt:`${MOTION}. Wide slow crane up; smoke from a small chimney drifts right.`,sound:'虫の声、柔らかなサックス'},
  {id:15,time:'03:35–03:52',duration:17,chapter:'ACT 3',visual:'戦後、畑が再び芝生や駐車場へ戻る。',narration:'戦争が終わると、多くの庭は元の姿へ戻りました。便利な時代が、土の記憶を覆っていきます。',imagePrompt:`${STYLE}. Layered transition from vegetable garden to manicured lawn and parking area, melancholy editorial illustration.`,videoPrompt:`${MOTION}. Slow cross-dissolve transformation; wind lines remain constant.`,sound:'テープ逆再生のような薄い音、低いピアノ'},
  {id:16,time:'03:52–04:07',duration:15,chapter:'ACT 3',visual:'スーパーマーケットの光る棚。',narration:'食べ物は、いつでも、どこでも買えるものになりました。',imagePrompt:`${STYLE}. Abundant modern supermarket aisle, highly ordered products, dramatic perspective, slightly uncanny calm.`,videoPrompt:`${MOTION}. Smooth center dolly; packaging stays unreadable.`,sound:'静かな店内音、ミニマルビート'},
  {id:17,time:'04:07–04:23',duration:16,chapter:'ACT 3',visual:'スマートフォンで配達を注文する指。',narration:'指先ひとつで届く便利さは、土から食卓までの距離を見えなくしました。',imagePrompt:`${STYLE}. Hand ordering groceries on a smartphone, background of dark kitchen, stencil delivery route line, no legible interface text.`,videoPrompt:`${MOTION}. Slow rack focus from fingertip to dark window; rain streaks move.`,sound:'タップ音、雨、ローファイハイハット'},
  {id:18,time:'04:23–04:39',duration:16,chapter:'ACT 3',visual:'畑と食卓の間に長い影。',narration:'私たちは、食べることを知っていても、育てることを忘れかけています。',imagePrompt:`${STYLE}. Symbolic long table separated from a distant field by an oversized graphic shadow, contemplative visual metaphor.`,videoPrompt:`${MOTION}. Slow pullback revealing the distance; wind lines bridge both sides.`,sound:'風、チェロの低音'},
  {id:19,time:'04:39–04:55',duration:16,chapter:'TURN',visual:'岡沢町の坂道。風が上ってくる。',narration:'けれど、忘れたものは、風が運び戻してくれることがあります。',imagePrompt:`${STYLE}. Sloped residential street in Okazawa at blue hour, warm windows, hand-drawn wind lines climbing the hill.`,videoPrompt:`${MOTION}. Camera slowly follows wind uphill; leaves roll along pavement.`,sound:'坂を抜ける風、コードが明るく転調'},
  {id:20,time:'04:55–05:12',duration:17,chapter:'TURN',visual:'黒い家の庭。アガベと石、まだ空いた土。',narration:'この庭は、完成された景色ではありません。これから物語が始まる、余白です。',imagePrompt:`${STYLE}. Modern black wooden house and partially built California dry garden, agave, rocks and open soil, cinematic night lighting.`,videoPrompt:`${MOTION}. Slow reveal from rock foreground to house; spotlights glow.`,sound:'砂利を踏む音、落ち着いたビート'},
  {id:21,time:'05:12–05:27',duration:15,chapter:'TURN',visual:'ロストラータの葉を風の線がなぞる。',narration:'ロストラータの葉は、風の形を目に見えるものにします。',imagePrompt:`${STYLE}. Hero close-up of Yucca rostrata leaves illuminated at night, cream wind lines tracing the leaf geometry.`,videoPrompt:`${MOTION}. Leaves sway subtly; camera arcs slowly around the crown.`,sound:'細い葉が擦れる音'},
  {id:22,time:'05:27–05:43',duration:16,chapter:'TURN',visual:'コーヒーの湯気が左から右へ流れる。',narration:'湯気も、煙も、草の揺れも。この場所では、風が時間をゆっくり進めます。',imagePrompt:`${STYLE}. Ceramic coffee cup on a dark wooden deck, warm window light, steam flowing right like drawn stencil lines, calm lo-fi scene.`,videoPrompt:`${MOTION}. Locked camera with subtle push-in; steam and wind lines drift continuously.`,sound:'湯気、カップを置く音、レコードノイズ'},
  {id:23,time:'05:43–06:00',duration:17,chapter:'ACT 4',visual:'小さなレイズドベッドの設計線。',narration:'ここに、食べられる庭を少しずつ重ねていきます。美しさと、役に立つことを、分けない庭です。',imagePrompt:`${STYLE}. Architectural sketch overlay showing a compact raised edible garden integrated with agave and stone landscape.`,videoPrompt:`${MOTION}. Design lines draw themselves slowly; real garden appears beneath.`,sound:'鉛筆、紙、静かなビート'},
  {id:24,time:'06:00–06:16',duration:16,chapter:'ACT 4',visual:'レモン、ハーブ、ブルーベリーの苗。',narration:'レモン、ハーブ、ブルーベリー。毎日の食卓へ戻せる植物から始めます。',imagePrompt:`${STYLE}. Lemon sapling, herbs and blueberry plants arranged in a premium dry garden nursery composition, warm side light.`,videoPrompt:`${MOTION}. Slow tabletop-style glide; leaves move in the breeze.`,sound:'葉音、軽いマリンバ'},
  {id:25,time:'06:16–06:32',duration:16,chapter:'ACT 4',visual:'子どもの手と大人の手が同じ苗を植える。',narration:'育てることは、正解を教えることではありません。一緒に待つ時間をつくることです。',imagePrompt:`${STYLE}. Adult and child hands planting one seedling together, intimate close-up, amber light, rich soil texture.`,videoPrompt:`${MOTION}. Slow macro movement; hands press soil, wind lifts a small leaf.`,sound:'土、静かな息、ピアノ'},
  {id:26,time:'06:32–06:49',duration:17,chapter:'ACT 4',visual:'雨水が石を伝い、土へ入る断面。',narration:'雨を受け、土に蓄え、根へ渡す。庭は、小さな循環をつくります。',imagePrompt:`${STYLE}. Artistic cutaway of rain moving over rocks into soil and roots, educational but cinematic editorial illustration.`,videoPrompt:`${MOTION}. Water traces slowly through the cutaway; roots glow subtly.`,sound:'雨、水滴、低いシンセパッド'},
  {id:27,time:'06:49–07:05',duration:16,chapter:'ACT 4',visual:'虫、鳥、花がつながる小さな生態系。',narration:'花が虫を呼び、虫が鳥を呼び、庭が街の中に小さな生態系を取り戻します。',imagePrompt:`${STYLE}. Pollinator, small bird, herbs and flowers connected in a calm ecological scene, tasteful graphic lines.`,videoPrompt:`${MOTION}. Slow pan; bee, leaves and bird move minimally and naturally.`,sound:'鳥、蜂の羽音、柔らかなギター'},
  {id:28,time:'07:05–07:22',duration:17,chapter:'ACT 4',visual:'夜のテーブル。庭で採れたハーブと料理、ワイン。',narration:'そして夜には、庭の香りが食卓へ戻ります。ここは畑であり、静かなワインバーでもある。',imagePrompt:`${STYLE}. Elegant outdoor table at night with food, herbs and wine, modern black house and dry garden behind, intimate amber lighting.`,videoPrompt:`${MOTION}. Slow cinematic orbit; candle flame and herb leaves move in wind.`,sound:'グラス、遠いジャズ、風'},
  {id:29,time:'07:22–07:38',duration:16,chapter:'ACT 5',visual:'過去のVictory Gardenと現在の岡沢町が二重露光になる。',narration:'80年前の勝利の庭と、今ここにつくる庭。目的は違っても、根にあるものは同じです。',imagePrompt:`${STYLE}. Double exposure blending 1940s victory garden with contemporary Okazawa dry garden, elegant historical transition.`,videoPrompt:`${MOTION}. Slow dissolve between eras while wind lines remain continuous.`,sound:'昔のラジオが現代ビートへ溶ける'},
  {id:30,time:'07:38–07:54',duration:16,chapter:'ACT 5',visual:'一粒の種を掌に載せる。',narration:'自分の手で、何かを育てられる。その感覚は、数字では測れない安心になります。',imagePrompt:`${STYLE}. Single seed resting in an open palm, dramatic warm spotlight, deep navy background, minimalist composition.`,videoPrompt:`${MOTION}. Very slow push-in; faint dust and wind lines cross frame.`,sound:'心拍に近い低音、静寂'},
  {id:31,time:'07:54–08:10',duration:16,chapter:'ACT 5',visual:'街の複数の庭に灯りがともる。',narration:'ひとつの庭は小さい。でも、小さな庭が街に増えれば、それは新しい風景になります。',imagePrompt:`${STYLE}. Hillside Yokohama neighborhood at night, multiple small gardens glowing warmly, connected by subtle wind lines.`,videoPrompt:`${MOTION}. Slow aerial rise; garden lights appear one by one.`,sound:'広がるパッド、遠い街音'},
  {id:32,time:'08:10–08:25',duration:15,chapter:'ACT 5',visual:'植物の間を風が抜け、線が画面をつなぐ。',narration:'風は、境界を知りません。庭から庭へ、物語から物語へ、静かに渡っていきます。',imagePrompt:`${STYLE}. Wind lines traveling through yucca, olive and herbs across connected garden spaces, poetic wide composition.`,videoPrompt:`${MOTION}. Follow the wind lines across plants; gentle match cuts.`,sound:'風を主役に、音楽を一度薄くする'},
  {id:33,time:'08:25–08:40',duration:15,chapter:'ENDING',visual:'完成前の庭を正面から静かに見つめる。',narration:'この庭は、まだ始まったばかりです。',imagePrompt:`${STYLE}. Straight-on quiet night view of the unfinished but beautiful Okazawa garden, black house, warm light, large sky.`,videoPrompt:`${MOTION}. Almost static shot; only wind, smoke and plant motion.`,sound:'虫の声、遠いピアノ'},
  {id:34,time:'08:40–08:54',duration:14,chapter:'ENDING',visual:'土、芽、ロストラータ、食卓を短くつなぐ。',narration:'土を整え、種を植え、待ち、食べる。そのひとつひとつを、ここに記録していきます。',imagePrompt:`${STYLE}. Four-panel cinematic montage of soil, sprout, yucca and dinner table, unified color and shadow.`,videoPrompt:`${MOTION}. Slow rhythmic montage with soft crossfades, no fast cuts.`,sound:'主題メロディーの回帰'},
  {id:35,time:'08:54–09:06',duration:12,chapter:'ENDING',visual:'夜空の余白。風の線だけが流れ、タイトルが入る想定。',narration:'Every Garden Has a Story. すべての庭には、物語がある。',imagePrompt:`${STYLE}. Vast deep navy night sky above the left-weighted black house and illuminated garden, clean right-side copy space, elegant wind lines.`,videoPrompt:`${MOTION}. Slow pullback; wind lines drift into open sky.`,sound:'ロゴ用の短い音、風'},
  {id:36,time:'09:06–09:15',duration:9,chapter:'NEXT',visual:'朝の光を受ける小さな苗。',narration:'次回、土はどこから生まれるのか。岡沢町の庭づくりを、ゼロから始めます。',imagePrompt:`${STYLE}. Small seedling in first morning light, dark soil, hopeful warm glow, final teaser frame.`,videoPrompt:`${MOTION}. Dawn light slowly increases; leaf moves once in the breeze.`,sound:'鳥の一声、余韻',caption:'NEXT：土はどこから生まれるのか'}
];

export const episodeScript = ep01Scenes.map((scene) => scene.narration).join('\n\n');

export const youtubePack = {
  title: 'もし明日、食べ物が消えたら｜世界を救った「勝利の庭」と岡沢町の風',
  alternateTitles: [
    '戦争中、人々は庭で生き延びた｜Victory Gardenの記憶',
    'なぜ今、庭で食べ物を育てるのか｜岡沢町から始まる小さな循環'
  ],
  description: `もし明日、スーパーから食べ物が消えたら。\n\n第二次世界大戦中、人々は自宅の庭や学校、公園を畑へ変えました。それは「Victory Garden（勝利の庭）」と呼ばれ、食料だけでなく、安心と地域のつながりを育てました。\n\nSUNSET DECK第1話では、その歴史をたどりながら、横浜・岡沢町にこれからつくる庭の意味を考えます。風、土、光、食卓。静かなLo-Fiドキュメンタリーとしてお楽しみください。\n\nEvery Garden Has a Story.`,
  tags: ['Victory Garden','家庭菜園','食育','庭づくり','ドライガーデン','岡沢町','横浜','ロストラータ','サステナブル','LoFi','SUNSET DECK'],
  thumbnail: {
    headline: 'もし食べ物が消えたら',
    subline: '世界を救った庭の話',
    composition: '左60%に黒い家と照明されたロストラータ、右40%に暗い空とコピー余白。白い手描き風ラインを右方向へ流す。'
  }
};
